services:
  surrealdb:
    container_name: surrealdb
    image: surrealdb/surrealdb:latest
    command: start --log trace --user root --pass root
    ports:
      - "8000:8000"
    volumes:
      - surrealdb_data:/mydata
    environment:
      - SURREAL_LOG=trace
      - SURREAL_USER=root
      - SURREAL_PASS=root
    labels:
      com.docker.desktop.extension: "true"
      com.docker.desktop.extension.name: "SurrealDB"

  surrealist:
    container_name: surrealist
    image: surrealdb/surrealist:latest
    ports:
      - "8001:8080"
    depends_on:
      - surrealdb
    labels:
      com.docker.desktop.extension: "true"
volumes:
  surrealdb_data:
